// Accounting-module types (recurring journals, revaluation runs, settings).
import type { BaseRecord, ID } from '../../store';
import type { PostLine } from '../../store/engine';

export interface RecurringJournalLine {
  id: ID;
  accountId: ID;
  dr: number;
  cr: number;
  partyType?: 'Customer' | 'Supplier' | 'Employee';
  partyId?: ID;
  partyName?: string;
  dimensions?: Record<string, string>;
  narration?: string;
}

export interface RecurringJournal extends BaseRecord {
  code: string;
  name: string;
  frequency: 'Monthly' | 'Quarterly';
  startDate: string;
  endDate?: string;
  nextRun: string;
  /** 'Draft' creates draft journals for review; 'Post' posts directly (subject to period control) */
  mode: 'Draft' | 'Post';
  narration: string;
  lines: RecurringJournalLine[];
  status: 'Active' | 'Paused' | 'Ended';
  lastRunAt?: string;
  runCount: number;
  /** journals generated by this definition (ids) */
  generatedIds: ID[];
}

export interface RevaluationItem {
  id: ID;
  kind: 'AR' | 'AP' | 'Bank';
  ref: string;
  partyName?: string;
  accountId: ID;
  partyType?: 'Customer' | 'Supplier';
  partyId?: ID;
  currency: string;
  amount: number;
  bookRate: number;
  bookBase: number;
  closingBase: number;
  difference: number;
}

export interface RevaluationRun extends BaseRecord {
  number: string;
  asOf: string;
  period: string;
  currency: string;
  closingRate: number;
  rateId?: ID;
  scope: ('AR' | 'AP' | 'Bank')[];
  items: RevaluationItem[];
  gain: number;
  loss: number;
  net: number;
  journalId?: ID;
  journalNumber?: string;
  reversalJournalId?: ID;
  autoReverse: boolean;
  status: 'Posted' | 'Reversed';
  reason?: string;
}

export interface AccountingSettings {
  roundOffAccountId?: ID;
  fxGainAccountId?: ID;
  fxLossAccountId?: ID;
  unrealisedFxGainAccountId?: ID;
  unrealisedFxLossAccountId?: ID;
  retainedEarningsAccountId?: ID;
  openingBalanceEquityAccountId?: ID;
  defaultDimensions?: Record<string, string>;
  duplicateRules?: Record<string, { fields: string[]; mode: 'Block' | 'Warn' }>;
}

export type DraftLine = PostLine & { id: string; side: 'Dr' | 'Cr'; amount: number };
