// generated by scripts/storyset-fetch.mjs from scripts/storyset.manifest.json — do not edit
export const STORYSET_NAMES = ['accountant', 'add-friends', 'add-user', 'agreement', 'authentication', 'building', 'business-plan', 'calendar', 'celebration', 'checklist', 'coins', 'company', 'completed', 'contact-us', 'crm', 'currency', 'dashboard', 'data-report', 'documents', 'done', 'empty', 'error', 'factory', 'finance', 'folder', 'investing', 'invoice', 'loading', 'logistics', 'mobile-payments', 'no-access', 'no-connection', 'no-data', 'not-found', 'online-banking', 'order-confirmed', 'processing', 'savings', 'scrum-board', 'search', 'secure-login', 'server', 'settings', 'setup', 'startup-life', 'tax', 'upgrade', 'wallet'] as const;
export type StorysetName = (typeof STORYSET_NAMES)[number];
/** Entries the manifest expects an animated GIF for (animated/<name>.gif). */
export const STORYSET_ANIMATED: ReadonlySet<StorysetName> = new Set<StorysetName>(['celebration', 'completed', 'contact-us', 'error', 'finance', 'loading', 'no-connection', 'not-found', 'setup', 'upgrade']);
/** GIFs safe to show on dark surfaces without a .dark.gif sibling. */
export const STORYSET_DARK_OK: ReadonlySet<StorysetName> = new Set<StorysetName>([]);
